### ISSUE TITLE
Some API tweaking for openevse integration.

### ISSUE THREAD

**Issue by KipK** [firstof9/python-openevse-http#394]
Following up [#402](https://github.com/firstof9/openevse/issues/402), I create an issue here as its more appropriated.

1/ If a claim or an override is already present, API should add the property on it, instead of creating a new claim/override with only the latest property.

example: EVSE is manually set to enabled, user change the charge_rate, it then just create a new override with only "charge_current" , state is removed.
should instead create a new override with "charge_current" and "state"

2/ Same as above, If a claim/override have more than one property ( but auto_release ), removing a property should keep the other properties but not delete the claim/override. If there's only one property, it then should remove the override/claim.

3/ setting charge rate to its max value ( aka "max_current_soft" ) should remove the charge_current property from the override if there's other properties, or remove the override if there's only the "charge_current" one.

In all cases, it should not consider "auto_release" if set to "true" , as this one is always added to a claim/override by default. You can just ignore this property like it does on OpenEVSE UI side as there's no use case for override. But probably better to test the boolean state and just ignore it if it's true.

**Comment by firstof9** [comment]
> 1/ If a claim or an override is already present, API should add the property on it, instead of creating a new claim/override with only the latest property.

As I understand it the override API is just a single setting, and calling it again should just add to the override that's in place currently. As for the claims, a similar thing as long as the `client` is the same. Please do correct me if I am wrong.


> 3/ setting charge rate to its max value ( aka "max_current_soft" ) should remove the charge_current property from the override if there's other properties, or remove the override if there's only the "charge_current" one.

This shouldn't be too hard.

**Comment by firstof9** [comment]
Looking at the code for `make_claim`

https://github.com/firstof9/python-openevse-http/blob/6cc39e564223bcb5589f3cd385cd67c62daeb49c/openevsehttp/__main__.py#L776-L811

I'm only adjusting the claim the library makes and only adjusting whatever variables are passed, but that only piles on the current claim then I assume right or would it wipe what's currently in the claim and use what's been passed to it?

**Comment by KipK** [comment]
On OpenEvse each time you make a new claim with same service ID or an override, you have to resend all the properties yes.

**Comment by KipK** [comment]
To illustrate, here is a short video of the consequencies of this issue:


https://github.com/user-attachments/assets/4976a7f5-b8c0-401f-9f34-70787dc6bdf9

**Comment by KipK** [comment]
Hi @firstof9 ,

I saw your "fix_claims" branch, is it testable yet ?

**Comment by firstof9** [comment]
That branch was because I forgot I had technically fixed it in the integration 😆

**Comment by KipK** [comment]
I thought it was to fix `[this](https://github.com/firstof9/python-openevse-http/issues/394#issuecomment-2587006239)` , the lost properties when making a claim/override

**Comment by firstof9** [comment]
I thought it was working correctly with the integration now? Is that not the case?

**Comment by KipK** [comment]
nope it still removes the previous properties.

To reproduce:

Send an override to set the state to Active or Disabled depending of your default state.
Then set the charge rate using number.openevse_charge_rate
The previous Active/Disabled state is removed then.

**Comment by firstof9** [comment]
Ah ok then yes, the fix_claims branch will fix that.

**Comment by firstof9** [comment]
Ok you should be able to modify the `manifest.json` for the integration to `0.1.72` and that'll have the change in it.

**Comment by KipK** [comment]
Great, looks good here.  👍 :)

2 things:

- When charge rate is manually set, if it's manually set back to the max value, it should remove the charge_current prop override.
- When switching from Active/Disabled to Auto ( aka removing the state property from override, it actually remove the charge_current prop. 



I still get the websocket error posted on the other thread when restarting HA

```
Recorder: openevsehttp.__main__
Source: runner.py:154
First time appeared: 09:12:14 (244 occurrencies)
Last Recording: 09:12:14

Websocket to ws://192.168.1.8/ws failed, aborting [Error: '01JJ4VKJ7BGNTWN4BFD6PNF2MT']
```

Seems it tried to reconnect 244 times in 1 sec.

**Comment by firstof9** [comment]
> I still get the websocket error posted on the other thread when restarting HA, just posting it here as it's more related to the library than the integration I think.

It's actually the integration, again, I'm not sure how you are reaching that message, I cannot reproduce it.

> * When charge rate is manually set, if it's manually set back to the max value, it should remove the charge_current prop override.

I'll see what I can do.

> * When switching from Active/Disabled to Auto ( aka removing the state property from override, it actually remove the charge_current prop. Should keep it.

I'll take a look at that too. What service are you calling to toggle these?

**Comment by KipK** [comment]
> I'll take a look at that too. What service are you calling to toggle these?
I use set override for this

**Comment by KipK** [comment]
Just tested, it's ok with 5.1.2 but not with dev builds, I can reproduce now :)

**Comment by firstof9** [comment]
This branch will catch the error: https://github.com/firstof9/openevse/tree/key-check

**Comment by KipK** [comment]
Here  are the output:

```
2025-02-04 21:49:16.608 DEBUG (MainThread) [custom_components.openevse.services] Device ID: 1a8619b7019b8e42ea0f560a0c008fc0
2025-02-04 21:49:16.608 DEBUG (MainThread) [custom_components.openevse.services] Device_entry: DeviceEntry(area_id='garage', config_entries={'01JJ4VKJ7BGNTWN4BFD6PNF2MT', '01JC9Q0JN4GKXMN9K6VPGQFYW7'}, configuration_url='http://192.168.1.8/', connections={('openevse', '01J7BSHM4CWTVBXH5978MGEAMR'), ('openevse', '01JJ4VKJ7BGNTWN4BFD6PNF2MT')}, created_at=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), disabled_by=None, entry_type=None, hw_version=None, id='1a8619b7019b8e42ea0f560a0c008fc0', identifiers={('openevse', '9C9C1FD9D8E8')}, labels=set(), manufacturer='OpenEVSE', model='openevse_wifi_v1', model_id=None, modified_at=datetime.datetime(2025, 2, 4, 16, 58, 8, 505522, tzinfo=datetime.timezone.utc), name_by_user=None, name='openevse', primary_config_entry='01JJ4VKJ7BGNTWN4BFD6PNF2MT', serial_number=None, suggested_area=None, sw_version='master_d8a3474c', via_device_id=None, is_new=False, _cache={'json_repr': b'{"area_id":"garage","configuration_url":"http://192.168.1.8/","config_entries":["01JJ4VKJ7BGNTWN4BFD6PNF2MT","01JC9Q0JN4GKXMN9K6VPGQFYW7"],"connections":[["openevse","01J7BSHM4CWTVBXH5978MGEAMR"],["openevse","01JJ4VKJ7BGNTWN4BFD6PNF2MT"]],"created_at":0.0,"disabled_by":null,"entry_type":null,"hw_version":null,"id":"1a8619b7019b8e42ea0f560a0c008fc0","identifiers":[["openevse","9C9C1FD9D8E8"]],"labels":[],"manufacturer":"OpenEVSE","model":"openevse_wifi_v1","model_id":null,"modified_at":1738688288.505522,"name_by_user":null,"name":"openevse","primary_config_entry":"01JJ4VKJ7BGNTWN4BFD6PNF2MT","serial_number":null,"sw_version":"master_d8a3474c","via_device_id":null}'})
2025-02-04 21:49:16.609 DEBUG (MainThread) [custom_components.openevse.services] Config ID: 01J7BSHM4CWTVBXH5978MGEAMR
2025-02-04 21:49:16.609 ERROR (MainThread) [custom_components.openevse.services] Error locating configuration: '01J7BSHM4CWTVBXH5978MGEAMR'
2025-02-04 21:49:16.609 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139906833999344] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2795, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2838, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openevse/services.py", line 232, in _set_override
    response = await manager.set_override(
                     ^^^^^^^
UnboundLocalError: cannot access local variable 'manager' where it is not associated with a value
```

**Comment by firstof9** [comment]
Custom components override built in, did you have the built in one installed at some point?

**Comment by KipK** [comment]
Yes when I've first installed HA  and then saw it was the wrong integration and installed yours.

**Comment by KipK** [comment]
anyway, I've cleaned up my setup mess :)

Was not this easy, no idea how it could happend. probably by testing dev branches over the hacs installation. 

Thanks for your support. 


About my previous comment:

> When switching from Active/Disabled to Auto ( aka removing the state property from override, it actually remove the charge_current prop. Should keep it.

Forget this one. It seems Openevse firmware now do like this too, setting Auto clear the current limit so let's keep it this way.

**Comment by firstof9** [comment]
> too bad, I still have a problem at startup or when reloading the integration.

I'll catch that one as well, I'll update it in the morning. 
Thanks for all the testing.

**Comment by firstof9** [comment]
Changes pushed.

**Comment by KipK** [comment]
Here is it:

diagnostic: https://pastebin.com/jcppc9xW

logs:

```
Recorder: openevsehttp.__main__
Source: runner.py:154
S'est produit pour la première fois: 16:01:30 (244 occurrences)
Dernier enregistrement: 16:01:30

Websocket to ws://192.168.1.8/ws failed, aborting [Error: cannot access local variable 'coordinator' where it is not associated with a value]

```

```
Recorder: openevsehttp.websocket
Source: /usr/local/lib/python3.13/site-packages/openevsehttp/websocket.py:128
S'est produit pour la première fois: 16:01:30 (1 occurrences)
Dernier enregistrement: 16:01:30

Unexpected exception occurred: cannot access local variable 'coordinator' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/openevsehttp/websocket.py", line 92, in running
    await self.callback(msgtype, msg, None)
  File "/usr/local/lib/python3.13/site-packages/openevsehttp/__main__.py", line 290, in _update_status
    await self.callback()  # pylint: disable=not-callable
    ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openevse/__init__.py", line 359, in websocket_update
    coordinator.async_set_updated_data(self._data)
    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'coordinator' where it is not associated with a value
```



Recorder: custom_components.openevse
Source: custom_components/openevse/__init__.py:357
intégration: OpenEVSE (documentation, problèmes)
S'est produit pour la première fois: 16:01:30 (1 occurrences)
Dernier enregistrement: 16:01:30

Error locating configuration: '01JKAVTFJW9RQ0ZTCVAXY0V6R2'


complete debug log:

https://pastebin.com/k0TkxsCS

**Comment by firstof9** [comment]
Thanks I see the problem, just an order of operations thing.
Changes pushed.

**Comment by KipK** [comment]
All good sir 👍  fixed
