### ISSUE TITLE
Unable to toggle "sleep mode" after upgrading to Hass 2022.4

### ISSUE THREAD

**Issue by Aephir** [firstof9/python-openevse-http#58]
Hi, as the title says, after I upgraded to Home Assistant v2022.4.x (tried a few different, I'm on 2022.4.5 now), I have not been able to call the "sleep mode" from Home Assistant.

It looks like it's getting updates from OpenEVSE (e.g. the "sensor.openevse_charging_current" sensor in Home Assistant changes when car is charging), but if I try to toggle the sleep mode, I get this notice:
<img width="918" alt="Screenshot 2022-04-16 at 11 13 00" src="https://user-images.githubusercontent.com/20152788/163669550-45035d0d-4cfd-42ba-8b4c-5ff8b6d65935.png">

I can see a few entries in the logs (OpenEVSE is conncted to, and reachable at http://10.0.20.27), this one seems to come every time I try to toggle sleep mode:

<details>

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/openevse/switch.py:98
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:15:27 (1 occurrences)
Last logged: 18:15:27

[140114950482000] 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
    await result
  File "/config/custom_components/openevse/switch.py", line 98, in async_turn_on
    await getattr(self._manager, self.toggle_command)()
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 440, in toggle_override
    response = await self.send_command(command)
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 237, in send_command
    value = await self.process_request(url=url, method="post", data=data)
  File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 208, in process_request
    message = await resp.json()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
```

</details>

I've also seen these a few times (though though it might only have been while using integration v2.1.1, before upgrading to the beta):

<details>

```
Logger: openevsehttp
Source: /usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py:143
First occurred: April 15, 2022, 19:32:15 (4 occurrences)
Last logged: April 15, 2022, 19:34:16

Websocket connection failed, retrying in 15s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 30s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 60s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
Websocket connection failed, retrying in 120s: Cannot connect to host 10.0.20.27:80 ssl:default [Connect call failed ('10.0.20.27', 80)]
```

</details>

as well as:

<details>

```
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:529
Integration: Sensor (documentation, issues)
First occurred: April 15, 2022, 12:09:06 (2 occurrences)
Last logged: April 15, 2022, 12:09:06

Error adding entities for domain sensor with platform openevse
Error while setting up openevse platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

</details>

and

<details>

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_registry.py:529
Integration: Binary sensor (documentation, issues)
First occurred: April 15, 2022, 12:09:06 (2 occurrences)
Last logged: April 15, 2022, 12:09:06

Error adding entities for domain binary_sensor with platform openevse
Error while setting up openevse platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 345, in async_get_or_create
    return self.async_update_entity(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 529, in async_update_entity
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance
```

</details>

I am on v2.1.2-b1 of the integration (seen from the file downloaded with the `download diagnostics` option from the integration page, though I first saw these issues before upgrading to the beta, while on v2.1.1).

**Comment by firstof9** [comment]
Please run the following in Home Assistant in the Dev-Tools -> Services tab:
![image](https://user-images.githubusercontent.com/1105672/163730402-bbd26b55-af90-4221-9673-801e4e2ee5b9.png)


```yaml
service: logger.set_level
data:
  openevsehttp: debug
```
and press 'Call Service'
![image](https://user-images.githubusercontent.com/1105672/163730438-bbaf17f7-7093-4dfd-a984-e27fb44b33be.png)

Then attempt to toggle sleep mode and report the extra debug data from the logs please.

**Comment by Aephir** [comment]
I didn't see anything starting with `DEBUG [openevsehttp] Toggle response:`, but there were 14 lines starting with `DEBUG` (7 for each toggle); all of that is pasted below.


<details>

```
2022-04-18 09:40:17 DEBUG (MainThread) [openevsehttp] Detected firmware: 3.3.1
2022-04-18 09:40:17 DEBUG (MainThread) [openevsehttp] Toggling manual override via RAPI
2022-04-18 09:40:17 DEBUG (MainThread) [openevsehttp] Posting data: $FE to http://10.0.20.27/r
2022-04-18 09:40:17 DEBUG (MainThread) [openevsehttp] Connecting to http://10.0.20.27/r with data payload of {'json': 1, 'rapi': '$FE'} using method post
2022-04-18 09:40:17 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140114966371920] 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
await result
File "/config/custom_components/openevse/switch.py", line 105, in async_turn_off
await getattr(self._manager, self.toggle_command)()
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 440, in toggle_override
response = await self.send_command(command)
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 237, in send_command
value = await self.process_request(url=url, method="post", data=data)
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 208, in process_request
message = await resp.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
2022-04-18 09:40:19 DEBUG (MainThread) [openevsehttp] Detected firmware: 3.3.1
2022-04-18 09:40:19 DEBUG (MainThread) [openevsehttp] Toggling manual override via RAPI
2022-04-18 09:40:19 DEBUG (MainThread) [openevsehttp] Posting data: $FE to http://10.0.20.27/r
2022-04-18 09:40:19 DEBUG (MainThread) [openevsehttp] Connecting to http://10.0.20.27/r with data payload of {'json': 1, 'rapi': '$FE'} using method post
2022-04-18 09:40:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140114966371920] 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 677, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 955, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 714, in _handle_entity_call
await result
File "/config/custom_components/openevse/switch.py", line 98, in async_turn_on
await getattr(self._manager, self.toggle_command)()
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 440, in toggle_override
response = await self.send_command(command)
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 237, in send_command
value = await self.process_request(url=url, method="post", data=data)
File "/usr/local/lib/python3.9/site-packages/openevsehttp/__init__.py", line 208, in process_request
message = await resp.json()
File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1103, in json
raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('http://10.0.20.27/r')
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Updating data from http://10.0.20.27/status
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Connecting to http://10.0.20.27/status with data payload of None using method get
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Status update: {'mode': 'STA', 'wifi_client_connected': 1, 'eth_connected': 0, 'net_connected': 1, 'ipaddress': '10.0.20.27', 'emoncms_connected': 1, 'packets_sent': 7446, 'packets_success': 7419, 'mqtt_connected': 0, 'ohm_hour': 'NotConnected', 'free_heap': 230376, 'comm_sent': 111466, 'comm_success': 89535, 'rapi_connected': 1, 'amp': 0, 'voltage': 240, 'pilot': 16, 'wh': 704158, 'temp1': False, 'temp2': 156, 'temp3': False, 'temp4': 257.5, 'state': 254, 'freeram': 230376, 'divertmode': 1, 'srssi': -82, 'elapsed': 395, 'wattsec': 1400623, 'watthour': 704158, 'gfcicount': 0, 'nogndcount': 0, 'stuckcount': 0, 'solar': 0, 'grid_ie': 0, 'charge_rate': 0, 'divert_update': 223461, 'ota_update': 0, 'time': '1970-01-20T01:43:58Z', 'offset': '+0100'}
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Updating data from http://10.0.20.27/config
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Connecting to http://10.0.20.27/config with data payload of None using method get
2022-04-18 09:40:20 DEBUG (MainThread) [openevsehttp] Config update: {'firmware': '5.0.1', 'protocol': '4.0.1', 'espflash': 4194304, 'version': '3.3.1', 'diodet': 0, 'gfcit': 1, 'groundt': 0, 'relayt': 0, 'ventt': 0, 'tempt': 1, 'service': 2, 'scale': 220, 'offset': 0, 'mqtt_supported_protocols': ['mqtt', 'mqtts'], 'http_supported_protocols': ['http', 'https'], 'ssid': 'aephir_iot', 'pass': '_DUMMY_PASSWORD', 'www_username': 'aephir', 'www_password': '_DUMMY_PASSWORD', 'hostname': 'openevse-4421', 'sntp_hostname': 'pool.ntp.org', 'time_zone': 'Europe/Copenhagen|CET-1CEST,M3.5.0,M10.5.0/3', 'emoncms_server': 'http://10.0.30.21:8003', 'emoncms_node': 'emontx', 'emoncms_apikey': '_DUMMY_PASSWORD', 'emoncms_fingerprint': '', 'mqtt_server': '10.0.30.21', 'mqtt_port': 1883, 'mqtt_topic': '', 'mqtt_user': 'homeassistant', 'mqtt_pass': '_DUMMY_PASSWORD', 'mqtt_solar': '', 'mqtt_grid_ie': 'emon/emonpi/power1', 'mqtt_vrms': 'emon/emonpi/vrms', 'mqtt_announce_topic': 'openevse/announce/4421', 'ohm': '', 'divert_attack_smoothing_factor': 0.4, 'divert_decay_smoothing_factor': 0.05, 'divert_min_charge_time': 600, 'tesla_username': '', 'tesla_password': '', 'tesla_vehidx': -1, 'flags': 9, 'emoncms_enabled': True, 'mqtt_enabled': False, 'mqtt_reject_unauthorized': True, 'ohm_enabled': False, 'sntp_enabled': True, 'tesla_enabled': False, 'divert_enabled': False, 'pause_uses_disabled': False, 'mqtt_protocol': 'mqtt', 'charge_mode': 'fast'}
```

</details>

**Comment by firstof9** [comment]
I don't suppose you happen to have `Postman` installed by chance do you?

**Comment by Aephir** [comment]
I don't. Why?

**Comment by firstof9** [comment]
I'd like to see the response your OpenEVSE is replying with when the command is sent.

**Comment by Aephir** [comment]
I just installed it, but you might need to tell me how to do that if you want it any time soon :)

Actually, can I run it on my laptop, or do I need to install it on my Ubuntu system (where the HassOS VM is running)?

**Comment by firstof9** [comment]
It can run on your laptop that's fine.

You'll want to have your screen POST to your openevse's URL here's an example:
Your's from the debug messages should be `http://10.0.20.27/r`

![image](https://user-images.githubusercontent.com/1105672/164016214-67382d5f-c3e3-40a3-a780-1d583d96c5b2.png)

Under body you want to enter the data from the debug log we collected:
`{'json': 1, 'rapi': '$FE'}`

If you have a username/password setup, you'll input that under "Authorization" using "Basic Auth":
![image](https://user-images.githubusercontent.com/1105672/164016474-cdfa49f8-0351-4560-ae71-4b2b651b2209.png)

Once all this is entered. Press the `Send` button on the right, you'll get the response in the very bottom window.

**Comment by Aephir** [comment]
OK, this is the response (hope I did it right):

```
<html>
<font size='20'>
	<font color=006666>Open</font><b>EVSE</b>
</font>
<p><b>Open Source Hardware</b>
	<p>RAPI Command Sent<p>Common Commands:<p>Set Current - $SC XX<p>Set Service Level - $SL 1 - $SL 2 - $SL A<p>Get
						Real-time Current - $GG<p>Get Temperatures - $GP<p>
								<p>
									<form method='get' action='r'><label><b><i>RAPI Command:</b></i></label><input id='rapi' name='rapi' length=32>
										<p><input type='submit'></form>
											<script type='text/javascript'>
												document.getElementById('rapi').focus();
											</script>
											<p>

</html>
```

**Comment by firstof9** [comment]
That looks about right, could you try with the command `$FS` rather than `$FE` and see what it reports?
Example: `{'json': 1, 'rapi': '$FS'}`

**Comment by firstof9** [comment]
Oh shoot, I think I know what's wrong.
Thanks for testing with me.

**Comment by firstof9** [comment]
A new beta version of the custom component will be released soon with the fix.
Thanks again!

**Comment by Aephir** [comment]
Great, happy to help!

**Comment by firstof9** [comment]
Let me know how it goes, based on my testing it _should_ be working properly.

**Comment by Aephir** [comment]
Oh, sorry, didn't notice your last reply. But it seems to work just fine, thanks!
